import type { Product } from "./schema";

type SeedProduct = Omit<Product, "createdAt">;

export const seedProducts: SeedProduct[] = [
  {
    id: "prod-cinnamon",
    slug: "ceylon-cinnamon-sticks",
    name: "Ceylon Cinnamon Sticks",
    description: "Fragrant true cinnamon quills hand-rolled in Sri Lanka, ideal for tea, curries, and baking.",
    category: "Pantry",
    priceCents: 185000,
    imageUrl: "/img/ceylon-cinnamon-sticks.png",
    stock: 30,
    featured: true,
  },
  {
    id: "prod-dumbara-cushion",
    slug: "handwoven-dumbara-cushion",
    name: "Handwoven Dumbara Cushion",
    description: "A textured cushion cover inspired by the traditional geometric weaving of the Dumbara valley.",
    category: "Home",
    priceCents: 495000,
    imageUrl: "/img/handwoven-dumbara-cushion.png",
    stock: 12,
    featured: true,
  },
  {
    id: "prod-tea",
    slug: "single-origin-ceylon-tea",
    name: "Single-Origin Ceylon Tea",
    description: "Bright, full-bodied loose-leaf black tea grown in the misty central highlands.",
    category: "Tea",
    priceCents: 220000,
    imageUrl: "/img/single-origin-ceylon-tea.png",
    stock: 40,
    featured: true,
  },
  {
    id: "prod-coconut-bowl",
    slug: "coconut-shell-serving-bowl",
    name: "Coconut Shell Serving Bowl",
    description: "A polished, food-safe serving bowl made from reclaimed coconut shell by local artisans.",
    category: "Home",
    priceCents: 145000,
    imageUrl: "/img/coconut-shell-serving-bowl.png",
    stock: 18,
    featured: false,
  },
  {
    id: "prod-kithul",
    slug: "kithul-treacle",
    name: "Pure Kithul Treacle",
    description: "Small-batch palm syrup with deep caramel notes, traditionally tapped and gently reduced.",
    category: "Pantry",
    priceCents: 195000,
    imageUrl: "/img/kithul-treacle.png",
    stock: 24,
    featured: true,
  },
  {
    id: "prod-tote",
    slug: "elephant-print-tote",
    name: "Elephant Print Tote Bag",
    description: "A sturdy reusable cotton tote featuring an original Sri Lankan elephant motif.",
    category: "Accessories",
    priceCents: 175000,
    imageUrl: "/img/elephant-print-tote.png",
    stock: 25,
    featured: false,
  },
  {
    id: "prod-spice-set",
    slug: "spice-garden-gift-set",
    name: "Spice Garden Gift Set",
    description: "A curated selection of roasted curry powder, chilli, turmeric, and pepper from island growers.",
    category: "Pantry",
    priceCents: 365000,
    imageUrl: "/img/spice-garden-gift-set.png",
    stock: 20,
    featured: true,
  },
  {
    id: "prod-batik-scarf",
    slug: "batik-silk-scarf",
    name: "Batik Silk Scarf",
    description: "A lightweight silk scarf individually wax-resist dyed in a tropical botanical pattern.",
    category: "Accessories",
    priceCents: 425000,
    imageUrl: "/img/batik-silk-scarf.png",
    stock: 10,
    featured: false,
  },
  {
    id: "prod-tuktuk",
    slug: "hand-carved-tuk-tuk",
    name: "Hand-Carved Tuk Tuk",
    description: "A playful wooden keepsake hand-carved and painted by a family-run workshop.",
    category: "Crafts",
    priceCents: 285000,
    imageUrl: "/img/hand-carved-tuk-tuk.png",
    stock: 15,
    featured: false,
  },
  {
    id: "prod-coconut-oil",
    slug: "virgin-coconut-oil",
    name: "Virgin Coconut Oil",
    description: "Cold-pressed virgin coconut oil made from fresh kernel without additives.",
    category: "Pantry",
    priceCents: 235000,
    imageUrl: "/img/virgin-coconut-oil.png",
    stock: 28,
    featured: false,
  },
  {
    id: "prod-beeralu-runner",
    slug: "beeralu-lace-table-runner",
    name: "Beeralu Lace Table Runner",
    description: "An elegant cotton table runner made using Sri Lanka's traditional bobbin-lace craft.",
    category: "Home",
    priceCents: 550000,
    imageUrl: "/img/beeralu-lace-table-runner.png",
    stock: 8,
    featured: false,
  },
  {
    id: "prod-coffee",
    slug: "ceylon-coffee-beans",
    name: "Ceylon Coffee Beans",
    description: "Medium-roast whole beans with chocolate and citrus notes, grown and roasted in Sri Lanka.",
    category: "Coffee",
    priceCents: 260000,
    imageUrl: "/img/ceylon-coffee-beans.png",
    stock: 22,
    featured: true,
  },
];
